name: Lead
version: '${project.version}'
main: to.lodestone.lead.LeadPlugin
api-version: '1.20'
authors: [Apollo30]
description: A lightweight plugin that creates visual teams showcased in Civilization or Battle Royale events. 
website: https://lodestone.to
load: STARTUP
depend:
  - CommandAPI
  - Bookshelf
