version: 12

# If verbose is true, the plugin will output more information to the console/admins.
verbose: false

# Maximum amount of players that can be added to a team.
max_team_size: 5

# If true, the players are allowed to hit each other.
friendly_fire: true

# If true, players will be assigned to a team automatically.
auto_assign: false

# How collisions will work per team.
# - ALWAYS: Players will always collide with each other.
# - NEVER: Players will never collide with each other.
# - FOR_OTHER_TEAMS: Players will collide with other teams, but not their own.
# - FOR_OWN_TEAM: Players will collide with their own team, but not other teams.
# Note: If TAB is installed, this value is redundant.
collidable: ALWAYS

# How nametag visibility will work per team.
# - ALWAYS: Nametags will always be visible.
# - NEVER: Nametags will never be visible.
# - FOR_OTHER_TEAMS: Nametags will be visible for other teams, but not their own.
# - FOR_OWN_TEAM: Nametags will be visible for their own team, but not other teams.
# Note: If TAB is installed, this value is redundant.
name_tag_visibility: ALWAYS

# By default, should the default team commands be publicly accessible?
# If false, the player will need the permission "lodestone.lead.manage" to use the commands.
is_public: true

# The font to use for display names.
# If you are using custom fonts, you can specify the font name here.
font: null

# Should Lead color the player names?
# If enabled, player chat names will be colored based on their team color.
color_names: false

# How many teams can be created?
max_teams: 1000

# If true, Lead will increment the next available team number. Otherwise, it will be random.
should_increment: false # If true, and the generator type is NUMBER, the number will increment by 1 each time a team is created.

# Command Permissions
# Setting the permission to "null" will make the command publicly accessible.
# It is recommended to use LuckPerms or another permission plugin to manage permissions.
permissions:
  team: null
  teammsg: null
commands:
  help: null
  list: null
  edit: null
  kick: null
  invite: null
  create: null
  join: null
  leave: null
  disband: null
  chat: null
  shuffle: "lodestone.lead.manage"
  spawn: "lodestone.lead.manage"
  teleport: "lodestone.lead.manage"
  friendly_fire: "lodestone.lead.manage"
  nametag: "lodestone.lead.manage"
  collidable: "lodestone.lead.manage"
  merge: "lodestone.lead.manage"
  place: "lodestone.lead.manage"
  remove: "lodestone.lead.manage"
  delete: "lodestone.lead.manage"
  id: "lodestone.lead.manage"
  display_name: "lodestone.lead.manage"
  color: "lodestone.lead.manage"
