#######################################################################
#                       General Configuration                         #
#  DO NOT TOUCH VERSION! YOU MAY BREAK YOUR CONFIGURATION IF YOU DO!  #
#######################################################################
debug: false
update: true
version: 7
max_team_size: 5
default: # What the default setting is for whenever someone creates a team.
  friendly_fire: true
  collidable: ALWAYS # Options: ALWAYS, NEVER, FOR_OTHER_TEAMS, FOR_OWN_TEAM
  name_tag_visibility: ALWAYS # Options: ALWAYS, NEVER, FOR_OTHER_TEAMS, FOR_OWN_TEAM
  is_public: true # Will team commands be public or private?
max_teams: 1000 # The maximum amount of teams that can be created.
automatic_updates: true # If false, you will need to manually update the player tab using /team update.
color_names: false # If true, player names will be colored.
font: "default" # The font to use for display names.
set_temporary_group: true # If true, Lead will attempt to set the temporary group for TAB. Remember you need to configure TAB first!

# Command Permission
# Setting the permission to "null" will make the command public.
commands:
  help: null
  list: null
  edit: null
  kick: null
  invite: null
  create: null
  join: null
  leave: null
  disband: null
  chat: null
  teleport: "lodestone.lead.manage"
  friendly_fire: "lodestone.lead.manage"
  nametag: "lodestone.lead.manage"
  collidable: "lodestone.lead.manage"
  merge: "lodestone.lead.manage"
  place: "lodestone.lead.manage"
  remove: "lodestone.lead.manage"
  delete: "lodestone.lead.manage"
  id: "lodestone.lead.manage"
  display_name: "lodestone.lead.manage"
  color: "lodestone.lead.manage"
