name: Lead
version: '1.2.55'
main: gg.lode.lead.LeadPlugin
api-version: '1.21'
authors: [Apollo30]
description: A lightweight plugin that creates visual teams showcased in Civilization or Battle Royale events. 
website: https://lode.gg/
softdepend:
  - TAB
  - Bookshelf
  - PlaceholderAPI
folia-supported: true