name: Lead
version: '1.2.2'
main: to.lodestone.lead.LeadPlugin
api-version: '1.20'
authors: [Apollo30]
description: A lightweight plugin that creates visual teams showcased in Civilization or Battle Royale events. 
website: https://lode.gg/
depend:
  - CommandAPI
  - Bookshelf
softdepend:
  - TAB
  - PlaceholderAPI